[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "astro dev"
  targetPort = 4321

[[redirects]]
  from = "/rss.xml"
  to = "https://api.riverside.com/hosting/Vx6O326l.rss"
  status = 302
